### ISSUE TITLE
Figure out Hyper-V

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#406] opened 2020-07-28 21:27 UTC
This topic has come up in a few conversations over time but I want to open an issue to track our understanding of the situation.

About half or more of our users each year seem to be running a Windows host. Our image is distributed only as an OVA and is specifically built to work with VirtualBox. Windows has more and more things that make use of Hyper-V features. Hyper-V steals the lock on VT-x and won't share it with VirtualBox. This makes VirtualBox rather upset. In the worst case, it means that a VM won't launch but the error message looks rather similar to the same message we get when VT-x is disabled in BIOS.

Some things that are currently using features of Hyper-V:
- WSL2
- Device Guard
- Credential Guard
- Sandbox

The other option is to ensure that the Windows Hypervisor Platform feature (`VirtualMachinePlatform`) is enabled. This isn't perfect, though. When doing this, VirtualBox runs in slow mode. It's not as slow as setting `VBoxInternal/NEM/UseRing0Runloop` to `0` but it is still extremely slow. I can't get the sp20a image to boot with turtle mode enabled. Despite the fact that VirtualBox has claimed to work happily with Hyper-V since 6.0, there are [20 pages](https://forums.virtualbox.org/viewtopic.php?f=6&t=90853) on the forum that suggest otherwise.

I am assuming it's very likely that several people will come into CS 101 or their first UUG meeting having experimented with Docker or WSL2 or something else. At least being aware of causes and paths forward will be important going into the semester.

WSL2 and VirtualMachinePlatform _should_ be available on all editions of Windows 10; however, Hyper-V itself is only available on Pro and higher tiers.

Stopping WSL2 isn't enough to prevent it from clogging up VBox. It needs to actually be disabled.

Turtle Mode: 
![image](https://user-images.githubusercontent.com/850893/88724142-03a78b00-d0f8-11ea-9c0f-4768cfd1b0b9.png)
WSL2 Stopped: 
![image](https://user-images.githubusercontent.com/850893/88724284-33569300-d0f8-11ea-95ac-9f1c1da14475.png)

**Comment by Jonathing** [comment] 2020-09-17 01:08
We talked about this in the Teams chat, but I'll relay some of the stuff we talked about in there in here.

### Hyper-V Compatability Requirements

VMware and Oracle have added Hyper-V compatibility into VMware Workstation 15.5.5 and VirtualBox 6.1. The problem is that this can only be done with the following conditions [according to VMware](https://kb.vmware.com/s/article/76918):
- Your Windows version must be at least 2004 (or build 19041.264+).
- Your CPU needs to have an Intel Sandy Bridge (generally on most new Intel CPU's) or needs to be an AMD Bulldozer or newer.

### What happens if you don't meet the requirements

If your Windows 10 version isn't 2004, VirtualBox will still try to run the VM, albeit with a mountain of problems when using ansible or when trying to load some GNOME elements on the screen (i.e. the taskbar disappears on certain resolutions). VMware Workstation will just straight up refuse to launch the VM. I've personally downgraded my installation of Pengwin Linux to WSL1 to compensate for this, but that's only because I'm still on Windows 10 version 1909 since some of my hardware is considered buggy on version 2004.

**Comment by ripleymj** [comment] 2020-09-17 20:59
I just wanted to run through here in an unhelpful manner. Any time I'd tried VirtualBox's supposed support for co-existing with Hyper-V, it was slow to the point of being unusable (20+ minutes to not even reach the desktop). As of this week's test build, things now seem slightly sluggish, though usable, for the first time.

![2020-09-16](https://user-images.githubusercontent.com/12940106/93527487-f1331c00-f906-11ea-95f2-cfdf3387f5b5.jpg)

**Comment by ripleymj** [comment] 2021-05-31 14:55
It seems like recent versions of both Windows and VirtualBox have enabled this to work, so I'm closing this for now.

**Closed by ripleymj** 2021-05-31 14:55 UTC
